package app.lyricsapp;

public abstract class Language {
    public String type_of_language;
    public String mainMenu;
    public String findByLyric ;
    public String favoris ;
    public String exit ;
    public String choice;
    public String invaliedCommande ;
    public String reDo ;
    public String searchedByMusic ;
    public String searchedByArtistMusic;
    public String searchedByLyrics;
    public String searchedByArtist ;
    public String searchedWithLyrics ;
    public String enterArtistName ;
    public String errorArtistName ;
    public String noFoundMusic;
    public String enterLyrics;
    public String errorLyrics ;
    public String choseByMusicNumber ;
    public String returnToMain ;
    public String newResearch ;
    public String choseByMusicNumber2 ;
    public String exited;
    public String delete ;
    public String addToFavotis ;
    public String creatPlaylist ;
    public String playlistManag ;
    public String namePlaylist ;
    public String emptyEntry ;
    public String errorNamePlaylist ;
    public String errorNamePlaylist1;
    public String choosePlaylist ;
    public String emptyFavoris ;
    public String displayFavoris ;
    public String removeSuceed ;
    public String choosePlaylist2 ;
    public String chooseMusic ;
    public String searchedwithLyrics;
}
