package app.lyricsapp;

public abstract class Language {
    public String type_of_language;
    public String mainMenu;
    public String languageChoice;
    public String findByLyric ;
    public String favoris ;
    public String playlistMenu;
    public String exit ;
    public String banWordCLI;
    public String banWordIs;
    public String choice;
    public String invaliedCommande ;
    public String reDo ;
    public String favoritesArtist;
    public String favoritesArtistPlaylist;
    public String favoritesArtistNotFound;
    public String searchedByMusic ;
    public String searchedByArtistMusic;
    public String searchedByLyrics;
    public String searchedByArtist ;
    public String searchedWithLyrics ;
    public String enterArtistName ;
    public String errorArtistName ;
    public String errorArtistNameTooLong;
    public String enterSongName;
    public String errorSongName;
    public String errorSongNameTooLong;
    public String noFoundMusic;
    public String enterLyrics;
    public String errorLyrics ;
    public String errorLyricsTooLong;
    public String choseByMusicNumber ;
    public String isSearchMusicPopular;
    public String returnToMain ;
    public String returnToPreviousMenu;
    public String newResearch ;
    public String choseByMusicNumber2 ;
    public String exited;
    public String delete ;
    public String addToFavotis ;
    public String creatPlaylist ;
    public String playlistManag1;
    public String playlistManag2;
    public String playlistChangeName;
    public String playlistDelete;
    public String namePlaylist ;
    public String emptyEntry ;
    public String errorNamePlaylist ;
    public String errorNamePlaylist1;
    public String choosePlaylist ;
    public String emptyFavoris ;
    public String displayFavoris ;
    public String removeSuceed ;
    public String choosePlaylist2 ;
    public String chooseMusic ;
    public String searchedwithLyrics;
    public String exitToPreviousMenu;
    public String likedMusic;
    public String changeTaken;
    public String changeNotTaken;
    public String playlistCreated;
    public String playlistNewName;
    public String isPlaylistDelete1;
    public String isPlaylistDelete2;
    public String emptyPlaylist;
    public String displayPlaylist;
    public String returnToPreviousMenuInt;
    public String showPlaylist;
}
